import {readJson,writeJson,saveCatalog,getJson,today} from './shared.mjs';
import {setTimeout as delay} from 'node:timers/promises';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{validate,countries}=require('../dist/catalog.js'),c=await readJson('dist/catalog.json'),day=today();
const excluded=new Set((await readJson('data/excluded-seasons.json',{items:[]})).items.map(x=>x.intlId));c.items=c.items.filter(x=>!excluded.has(x.intlId));
const byId=new Map(c.items.filter(x=>x.intlId).map(x=>[x.intlId,x])),chineseOnly=c.items.filter(x=>!x.intlId),found=new Map(),pages=[];
let metadata=await readJson('data/intl-metadata.json',{}),localized=await readJson('data/localized-metadata.json',{});
const age=value=>value?Math.floor((Date.parse(day)-Date.parse(value))/86400000):Infinity;
for(const locale of ['en_US','th_TH','id_ID','vi_VN','ms_MY']){let complete=false;for(let pn=1;pn<=250;pn++){const qs=new URLSearchParams({season_type:'1,4',pn:String(pn),ps:'50',s_locale:locale,platform:'web'});const j=await getJson('https://api.bilibili.tv/intl/gateway/web/v2/ogv/index/items_v2?'+qs);if(j.code!==0||!Array.isArray(j.data?.cards))throw new Error('Official anime index unavailable');for(const card of j.data.cards){const id=Number(card.season_id);if(id>0){const item=found.get(id)||{id,titles:[]};if(card.title&&!item.titles.includes(card.title))item.titles.push(card.title);item.cover=card.cover||item.cover;found.set(id,item);}}if(!j.data.has_next){complete=true;pages.push({locale,pages:pn,complete:true});break;}if(!j.data.cards.length)throw new Error('Incomplete pagination');await delay(1200);}if(!complete)throw new Error('Index pagination bound reached');console.log(JSON.stringify({phase:'index',locale,ids:found.size}));await delay(1200);}
const response=await fetch('https://www.bilibili.tv/sitemap/ogv-media-0.xml',{signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('Sitemap unavailable');const xml=await response.text(),sitemapIds=[...new Set([...xml.matchAll(/\/media\/(\d+)/g)].map(x=>Number(x[1])))];if(!sitemapIds.length)throw new Error('Sitemap empty');
const ids=[...new Set([...found.keys(),...sitemapIds,...byId.keys()])].filter(id=>!excluded.has(id));ids.sort((a,b)=>String(metadata[a]?.checkedAt||'').localeCompare(String(metadata[b]?.checkedAt||'')));let cursor=0,done=0,failed=0,added=0,zhCount=0,metadataRequests=0;
function apply(meta){const id=meta.id;if(excluded.has(id)||meta.available===false)return;const anime=[1,4].includes(Number(meta.type));const valid=Array.isArray(meta.regions)&&meta.regions.every(x=>typeof x==='string'),sea=valid&&meta.regions.some(x=>Object.hasOwn(countries,x));let item=byId.get(id);if(!item&&anime&&sea){item={intlId:id,cnId:null,title:meta.title,regions:[],regionSource:'unknown'};byId.set(id,item);added++;}if(item&&anime){item.officialTitle=meta.title;item.aliases=[...new Set([...(item.aliases||[]),...(found.get(id)?.titles||[]),meta.originName].filter(Boolean))];item.cover=found.get(id)?.cover||meta.cover||item.cover||'';item.catalogCheckedAt=meta.checkedAt;if(valid){item.regions=meta.regions;item.regionSource='official';item.regionCheckedAt=meta.checkedAt;}}}
async function worker(){while(cursor<ids.length){const id=ids[cursor++],previous=metadata[id],item=byId.get(id),pending=item&&(!item.cnId||item.release?.status!=='aired');const refresh=process.argv.includes('--refresh')||!previous||age(previous.checkedAt)>=7||pending&&age(previous.checkedAt)>=1;
 if(refresh&&metadataRequests<800){metadataRequests++;const j=await getJson('https://api.bilibili.tv/intl/gateway/web/v2/ogv/play/season_info?'+new URLSearchParams({season_id:String(id),platform:'web',s_locale:'en_US'})),s=j.data?.season;
 if(j.code===0&&Number(s?.season_id)===id){metadata[id]={id,title:s.title,description:s.description,originName:s.origin_name,cover:s.vertical_cover||s.horizontal_cover||previous?.cover||null,originAreas:s.area_names,styles:s.styles?.map(x=>x.title)||[],officialStart:s.player_date,officialEpisodeCount:s.total_episodes_text,contentCheckedAt:day,regions:s.limit_areas,type:s.season_type_enum,firstEpisode:s.first_episode?.episode_id||null,airDate:s.player_date,indexShow:s.index_show,isFinished:s.is_finished,totalEpisodes:s.total_episodes_text,checkedAt:day};}
 else{metadata[id]={...previous,id,available:false,errorCode:j.code,checkedAt:day};failed++;}await delay(1200);}
 apply(metadata[id]);const m=metadata[id];if(m?.available!==false&&[1,4].includes(Number(m?.type))&&byId.has(id)&&(!localized[id]||age(localized[id].checkedAt)>=7)&&zhCount<150){zhCount++;const j=await getJson('https://api.bilibili.tv/intl/gateway/web/v2/ogv/play/season_info?'+new URLSearchParams({season_id:String(id),platform:'web',s_locale:'zh_CN'})),s=j.data?.season;if(j.code===0&&Number(s?.season_id)===id)localized[id]={id,title:s.title,originName:s.origin_name,cover:s.vertical_cover||s.horizontal_cover||localized[id]?.cover||null,description:s.description,airDate:s.player_date,indexShow:s.index_show,isFinished:s.is_finished,totalEpisodes:s.total_episodes_text,originAreas:s.area_names,checkedAt:day};else localized[id]={...localized[id],id,available:false,code:j.code,checkedAt:day};await delay(1200);}
 done++;if(done%100===0)console.log(JSON.stringify({phase:'official-metadata',checked:done,total:ids.length,added,failed}));}}
await Promise.all(Array.from({length:2},worker));c.items=[...byId.values(),...chineseOnly];validate(c.items);c.meta.indexDiscovery={pages,uniqueIds:found.size,sitemapIds:sitemapIds.length,metadataChecked:done,unavailable:failed,checkedAt:day};c.meta.updatedAt=day;c.meta.liveNote='持续检查官方五种语言动画目录与影视站点地图；仅新增官方动画类型且地区字段含东南亚国家的条目。保留历史数据，目录不保证所有地区绝对完整。';await writeJson('data/intl-metadata.json',metadata);await writeJson('data/localized-metadata.json',localized);await saveCatalog(c);console.log(JSON.stringify({phase:'official-update-complete',added,records:c.items.length,failed,localized:zhCount}));
